# Run the command: kubectl apply -f ./deployment.yaml
# in order to create the deployment, replicas (pods), service, and ingress objects

# define a Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-executor
spec:
  selector:
    matchLabels:
      run: code-executor
  replicas: 5
  template:
    metadata:
      labels:
        run: code-executor
    spec:
      containers:
      - name: code-executor
        image: bruceskellator/code-executor:latest  
        ports:
        - containerPort: 8080
        resources:
          # limits:
          #   cpu: 500m
          requests:
            cpu: 200m
---
# define a Service
apiVersion: v1
kind: Service
metadata:
  name: code-executor
  labels:
    run: code-executor
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    run: code-executor
---
# define an Ingress 
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: code-executor
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: kubernetes.docker.internal
    http:
      paths:
      - path: "/code-executor"
        pathType: Prefix
        backend:
          service:
            name: code-executor
            port:
              number: 3000

# Do the following before creating HPA object:
# 1) define Ingress Controller
# kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.0.4/deploy/static/provider/cloud/deploy.yaml
# kubectl delete -A ValidatingWebhookConfiguration ingress-nginx-admission
# 2) create metrics server (.yaml file obtained manually from below github):
# (This line is just for the link, do next step) kubectl apply -f https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml
# kubectl apply -f ./components.yaml