services:
  nginx:
    depends_on:
      - executor1
      - executor2
    restart: always
    build:
      dockerfile: Dockerfile
      context: "./nginx-docker"
    ports:
      - "3050:80"

  executor1:
    build:
      dockerfile: Dockerfile
      context: "./app"
    volumes:
      - "./app:/usr/src/app"
      - "node_modules:/usr/src/app/node_modules"
    ports:
      - "3001:3000"
    expose:
      - "3000"

  executor2:
    build:
      dockerfile: Dockerfile
      context: "./app"
    volumes:
      - "./app:/usr/src/app"
      - "node_modules:/usr/src/app/node_modules"
    ports:
      - "3002:3000"
    expose:
      - "3000"
volumes:
  node_modules:
