apiVersion: apps/v1
kind: Deployment
metadata:
  name: docs
spec:
  selector:
    matchLabels:
      app: docs
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: docs
    spec:
      containers:
      - name: docs
        image: asia.gcr.io/peerprogram/docs:d0ed7f0-dirty-OJIMVR2D
        ports:
        - containerPort: 3003
        envFrom:
          - secretRef:
              name: prod
