apiVersion: apps/v1
kind: Deployment
metadata:
  name: docs
  labels:
    app: docs
spec:
  selector:
    matchLabels:
      app: docs
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: docs
    spec:
      containers:
      - name: docs
        # image: asia.gcr.io/peerprogram/docs:d3b4b05
        image: asia.gcr.io/peerprogram/docs:8ff3898-dirty-GC3UUTU3
        ports:
        - containerPort: 3003
        envFrom:
          - secretRef:
              name: prod
