apiVersion: v1
kind: Service
metadata:
  name: docs-service
  labels:
    app: docs-service
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3003
    name: docs-service
  selector:
    app: docs-deployment
