apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-executor
spec:
  selector:
    matchLabels:
      app: code-executor
  replicas: 2
  template:
    metadata:
      labels:
        app: code-executor
    spec:
      containers:
      - name: code-executor
        image: asia.gcr.io/peerprogram/code-executor
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        envFrom:
          - secretRef:
              name: prod
