name: Build app
on:
  pull_request:
    branches:
      - main

jobs:
  build-test:
    name: Build test
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Code Executor
        run: docker build
        working-directory: Code Executor/app

      - name: Build nginx
        run: docker build
        working-directory: Code Executor/nginx-docker

      - name: Build Docs
        run: docker build
        working-directory: Docs

      - name: Build Frontend
        run: docker build
        working-directory: Frontend

      - name: Build Sessions
        run: docker build
        working-directory: Sessions
