# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build and Deploy to GKE

on:
  pull_request:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: peer-program-cluster-1    # Add your cluster name here.
  GKE_ZONE: asia-southeast1  # Add your cluster zone here.
  DEPLOYMENT_NAME: gke-peerprogram # Add your deployment name here.

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-18.04
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          service_account_email: ${{ secrets.ACCOUNT_EMAIL }}
          project_id: ${{ secrets.GKE_PROJECT }}
          export_default_credentials: true

      # Configure Docker to use the gcloud command-line tool as a credential
      # helper for authentication
      - run: |-
          gcloud --quiet auth configure-docker

      # Get the GKE credentials so we can deploy to the cluster
      - uses: google-github-actions/get-gke-credentials@main
        with:
          cluster_name: peer-program-cluster-1
          location: asia-southeast1
          credentials: ${{ secrets.GKE_SA_KEY }}

      # Set up kustomize
      - name: Set up Kustomize
        run: |-
          curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64

      # Build, Push and deploy the Docker images
      - name: Code Executor Image
        run: |-
          chmod +x build.sh
          sudo ./build.sh
        working-directory: Code Executor/app

      - name: Reverse Proxy Image
        run: |-
          chmod +x build.sh
          sudo ./build.sh
        working-directory: Code Executor/nginx-docker

      - name: Docs Image
        run: |-
          chmod +x build.sh
          sudo ./build.sh
        working-directory: Docs

      - name: Frontend Image
        run: |-
          chmod +x build.sh
          sudo ./build.sh
        working-directory: Frontend

      - name: Sessions Image
        run: |-
          chmod +x build.sh
          sudo ./build.sh
        working-directory: Sessions
