# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build and Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup gcloud auth activate-service-account
      - run: gcloud auth activate-service-account ${{ secrets.ACCOUNT_EMAIL }} --key-file ${{ secrets.GKE_SA_KEY }}

      # Configure Docker to use the gcloud command-line tool as a credential
      # helper for authentication
      - run: |-
          gcloud --quiet auth configure-docker

      # Build and Push the Docker images
      - name: Code Executor Image
        run: |-
          chmod +x build.sh
          sudo ./build.sh
        working-directory: Code Executor/app

      # Deploy to GCP
      - name: Deploy
        run: |-
          kubectl create secret generic prod ${{ secrets.PRODUCTION }}
          kubectl create secret tls onlyduh-tls-secrets --cert ${{ secrets.SECRET_CRT }} --key=${{ secrets.SECRET_KEY }}
          kubectl apply -f '01 - docs-deployment.yml'
          kubectl apply -f '02 - docs-service.yml'
        working-directory: kubernetes
